-- Tabla Principal: cotizaciones
CREATE TABLE IF NOT EXISTS public.cotizaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    sucursal_id bigint NOT NULL REFERENCES public.sucursales(id),
    cliente_id bigint REFERENCES public.clientes(id),
    total numeric DEFAULT 0 NOT NULL,
    vendedor_id uuid REFERENCES auth.users(id),
    estado text DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'convertida', 'cancelada')),
    vigencia timestamp with time zone DEFAULT (timezone('utc'::text, now()) + interval '15 days')
);

-- Tabla de Detalles: cotizacion_detalles
CREATE TABLE IF NOT EXISTS public.cotizacion_detalles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id bigint NOT NULL REFERENCES public.cotizaciones(id) ON DELETE CASCADE,
    producto_id bigint NOT NULL REFERENCES public.productos(id),
    cantidad int NOT NULL CHECK (cantidad > 0),
    precio_unitario numeric NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Configurar Políticas RLS (Opcional, si usas RLS habilitado)
ALTER TABLE public.cotizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cotizacion_detalles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON public.cotizaciones FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.cotizacion_detalles FOR ALL TO authenticated USING (true);
