-- 1. Crear Tabla Kárdex
CREATE TABLE IF NOT EXISTS public.kardex (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    producto_id bigint NOT NULL REFERENCES public.productos(id),
    sucursal_id bigint NOT NULL REFERENCES public.sucursales(id),
    tipo_movimiento text NOT NULL CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA', 'AJUSTE', 'TRASPASO_ENTRADA', 'TRASPASO_SALIDA', 'VENTA', 'DEVOLUCION')),
    cantidad int NOT NULL,
    saldo_previo int NOT NULL,
    saldo_nuevo int NOT NULL,
    referencia_id uuid,
    usuario_id uuid REFERENCES auth.users(id)
);

-- Configurar RLS
ALTER TABLE public.kardex ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for authenticated users" ON public.kardex FOR ALL TO authenticated USING (true);


-- 2. Actualizar function realizar_venta
CREATE OR REPLACE FUNCTION public.realizar_venta(
    p_venta_detalles jsonb,
    p_sucursal_id bigint,
    p_total numeric,
    p_metodo_pago text DEFAULT 'contado',
    p_cliente_id uuid DEFAULT NULL,
    p_usuario_id uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
AS $function$
DECLARE
    v_venta_id uuid;
    v_detalle jsonb;
    v_producto_id bigint;
    v_cantidad int;
    v_precio_unitario numeric;
    v_stock_actual int;
    v_cliente_saldo numeric;
    v_cliente_limite numeric;
BEGIN
    -- Validaciones de Crédito
    IF p_metodo_pago = 'credito' THEN
        IF p_cliente_id IS NULL THEN
            RAISE EXCEPTION 'Para ventas a crédito, se requiere un ID de cliente.';
        END IF;

        -- Obtener saldo y límite
        SELECT saldo_pendiente, limite_credito INTO v_cliente_saldo, v_cliente_limite
        FROM clientes 
        WHERE id = p_cliente_id;

        IF NOT FOUND THEN
             RAISE EXCEPTION 'Cliente no encontrado.';
        END IF;

        IF (v_cliente_saldo + p_total) > v_cliente_limite THEN
             RAISE EXCEPTION 'El cliente ha superado su límite de crédito.';
        END IF;

        -- Actualizar saldo cliente
        UPDATE clientes 
        SET saldo_pendiente = saldo_pendiente + p_total 
        WHERE id = p_cliente_id;
    END IF;

    -- 1. Insertar Venta
    INSERT INTO ventas (sucursal_id, total, created_at, metodo_pago, cliente_id, vendedor_id)
    VALUES (p_sucursal_id, p_total, now(), p_metodo_pago, p_cliente_id, p_usuario_id)
    RETURNING id INTO v_venta_id;

    -- 2. Procesar Detalles y Kardex
    FOR v_detalle IN SELECT * FROM jsonb_array_elements(p_venta_detalles)
    LOOP
        v_producto_id := (v_detalle->>'producto_id')::bigint;
        v_cantidad := (v_detalle->>'cantidad')::int;
        v_precio_unitario := (v_detalle->>'precio_unitario')::numeric;

        -- Insertar detalle
        INSERT INTO venta_detalles (venta_id, producto_id, cantidad, precio_unitario)
        VALUES (v_venta_id, v_producto_id, v_cantidad, v_precio_unitario);

        -- Leer stock anterior
        SELECT stock_actual INTO v_stock_actual FROM inventario 
        WHERE producto_id = v_producto_id AND sucursal_id = p_sucursal_id;

        -- Actualizar Inventario (Restar Stock)
        UPDATE inventario
        SET stock_actual = stock_actual - v_cantidad
        WHERE producto_id = v_producto_id AND sucursal_id = p_sucursal_id;
        
        -- Validar stock negativo
        IF (v_stock_actual - v_cantidad) < 0 THEN
            RAISE EXCEPTION 'Stock insuficiente para el producto ID %', v_producto_id;
        END IF;

        -- INSERTAR EN KARDEX
        INSERT INTO kardex (producto_id, sucursal_id, tipo_movimiento, cantidad, saldo_previo, saldo_nuevo, referencia_id, usuario_id)
        VALUES (v_producto_id, p_sucursal_id, 'VENTA', v_cantidad, v_stock_actual, v_stock_actual - v_cantidad, v_venta_id, p_usuario_id);

    END LOOP;

    RETURN json_build_object('success', true, 'venta_id', v_venta_id);
END;
$function$;


-- 3. Actualizar función transferir_inventario
CREATE OR REPLACE FUNCTION public.transferir_inventario(
    p_producto_id bigint,
    p_sucursal_origen_id bigint,
    p_sucursal_destino_id bigint,
    p_cantidad integer,
    p_usuario_id uuid DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $function$
DECLARE
    v_stock_origen integer;
    v_stock_destino integer;
    v_traspaso_id uuid;
BEGIN
    SELECT stock_actual INTO v_stock_origen
    FROM inventario
    WHERE producto_id = p_producto_id AND sucursal_id = p_sucursal_origen_id;

    IF v_stock_origen IS NULL OR v_stock_origen < p_cantidad THEN
        RAISE EXCEPTION 'Stock insuficiente en la sucursal de origen.';
    END IF;

    -- Crear Traspaso Log
    INSERT INTO traspasos (producto_id, origen_id, destino_id, cantidad, usuario_id, status)
    VALUES (p_producto_id, p_sucursal_origen_id, p_sucursal_destino_id, p_cantidad, p_usuario_id, 'completado')
    RETURNING id INTO v_traspaso_id;

    -- Update Origen
    UPDATE inventario
    SET stock_actual = stock_actual - p_cantidad
    WHERE producto_id = p_producto_id AND sucursal_id = p_sucursal_origen_id;

    -- Kardex Origen
    INSERT INTO kardex (producto_id, sucursal_id, tipo_movimiento, cantidad, saldo_previo, saldo_nuevo, referencia_id, usuario_id)
    VALUES (p_producto_id, p_sucursal_origen_id, 'TRASPASO_SALIDA', p_cantidad, v_stock_origen, v_stock_origen - p_cantidad, v_traspaso_id, p_usuario_id);

    -- Check Destino
    SELECT stock_actual INTO v_stock_destino
    FROM inventario
    WHERE producto_id = p_producto_id AND sucursal_id = p_sucursal_destino_id;

    IF FOUND THEN
        UPDATE inventario
        SET stock_actual = stock_actual + p_cantidad
        WHERE producto_id = p_producto_id AND sucursal_id = p_sucursal_destino_id;

        -- Kardex Destino (Update)
        INSERT INTO kardex (producto_id, sucursal_id, tipo_movimiento, cantidad, saldo_previo, saldo_nuevo, referencia_id, usuario_id)
        VALUES (p_producto_id, p_sucursal_destino_id, 'TRASPASO_ENTRADA', p_cantidad, v_stock_destino, v_stock_destino + p_cantidad, v_traspaso_id, p_usuario_id);
    ELSE
        INSERT INTO inventario (producto_id, sucursal_id, stock_actual, stock_minimo)
        VALUES (p_producto_id, p_sucursal_destino_id, p_cantidad, 5);

        -- Kardex Destino (Insert)
        INSERT INTO kardex (producto_id, sucursal_id, tipo_movimiento, cantidad, saldo_previo, saldo_nuevo, referencia_id, usuario_id)
        VALUES (p_producto_id, p_sucursal_destino_id, 'TRASPASO_ENTRADA', p_cantidad, 0, p_cantidad, v_traspaso_id, p_usuario_id);
    END IF;
END;
$function$;
