-- 1. Create 'clientes' table (from previous step)
CREATE TABLE IF NOT EXISTS public.clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    nombre text NOT NULL,
    telefono text,
    saldo_pendiente numeric DEFAULT 0,
    limite_credito numeric DEFAULT 5000
);

-- 2. Create 'turnos' table (NEW)
CREATE TABLE IF NOT EXISTS public.turnos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal_id bigint NOT NULL, -- references sucursales(id)
    usuario text, -- e.g. 'cajero1' or auth.uid()
    fecha_inicio timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    fecha_fin timestamp with time zone,
    monto_inicial numeric DEFAULT 0,
    monto_final_real numeric DEFAULT 0,
    total_ventas_efectivo numeric DEFAULT 0,
    total_ventas_tarjeta numeric DEFAULT 0,
    total_ventas_credito numeric DEFAULT 0,
    diferencia numeric DEFAULT 0
);

-- 3. Drop existing function to recreate with new parameters
DROP FUNCTION IF EXISTS public.realizar_venta;

-- 4. Create updated 'realizar_venta' function
CREATE OR REPLACE FUNCTION public.realizar_venta(
    p_venta_detalles jsonb,
    p_sucursal_id bigint,
    p_total numeric,
    p_metodo_pago text DEFAULT 'contado',
    p_cliente_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
AS $function$
DECLARE
    v_venta_id bigint;
    v_detalle jsonb;
    v_producto_id bigint;
    v_cantidad int;
    v_precio_unitario numeric;
    v_stock_actual int;
    v_cliente_saldo numeric;
    v_cliente_limite numeric;
BEGIN
    -- Validaciones de Crédito
    IF p_metodo_pago = 'credito' THEN
        IF p_cliente_id IS NULL THEN
            RAISE EXCEPTION 'Para ventas a crédito, se requiere un ID de cliente.';
        END IF;

        -- Obtener saldo y límite
        SELECT saldo_pendiente, limite_credito INTO v_cliente_saldo, v_cliente_limite
        FROM clientes 
        WHERE id = p_cliente_id;

        IF NOT FOUND THEN
             RAISE EXCEPTION 'Cliente no encontrado.';
        END IF;

        IF (v_cliente_saldo + p_total) > v_cliente_limite THEN
             RAISE EXCEPTION 'El cliente ha superado su límite de crédito.';
        END IF;

        -- Actualizar saldo cliente
        UPDATE clientes 
        SET saldo_pendiente = saldo_pendiente + p_total 
        WHERE id = p_cliente_id;
    END IF;

    -- 1. Insertar Venta
    INSERT INTO ventas (sucursal_id, total, created_at, metodo_pago, cliente_id)
    VALUES (p_sucursal_id, p_total, now(), p_metodo_pago, p_cliente_id)
    RETURNING id INTO v_venta_id;

    -- 2. Procesar Detalles
    FOR v_detalle IN SELECT * FROM jsonb_array_elements(p_venta_detalles)
    LOOP
        v_producto_id := (v_detalle->>'producto_id')::bigint;
        v_cantidad := (v_detalle->>'cantidad')::int;
        v_precio_unitario := (v_detalle->>'precio_unitario')::numeric;

        -- Insertar detalle
        INSERT INTO venta_detalles (venta_id, producto_id, cantidad, precio_unitario)
        VALUES (v_venta_id, v_producto_id, v_cantidad, v_precio_unitario);

        -- Actualizar Inventario (Restar Stock)
        UPDATE inventario
        SET stock_actual = stock_actual - v_cantidad
        WHERE producto_id = v_producto_id AND sucursal_id = p_sucursal_id;
        
        -- Validar stock negativo (Opcional)
        SELECT stock_actual INTO v_stock_actual FROM inventario 
        WHERE producto_id = v_producto_id AND sucursal_id = p_sucursal_id;
        
        IF v_stock_actual < 0 THEN
            RAISE EXCEPTION 'Stock insuficiente para el producto ID %', v_producto_id;
        END IF;
    END LOOP;

    RETURN json_build_object('success', true, 'venta_id', v_venta_id);
END;
$function$;
